name: deploy to prod 

on: 
  workflow_dispatch:
    
env: 
  URL: prashansatw.github.io/demo-workflow-prod/

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{env.URL}}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'artifacts'

      - name: Setup JFrog CLI
        id: setup_JFrog_CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{secrets.JF_USER}}
          JF_PASSWORD: ${{secrets.JF_PASSWORD}}
      
      - run: |
          jf rt ping --url=https://dpga.jfrog.io/artifactory
      
      - name: Download Artifacts
        run: |
          jf rt dl prod-repo/build/build/

      - name: Checkout Dev Target 
        uses: actions/checkout@v2
        with:
          repository: prashansatw/demo-workflow-prod
          path: "deploy"
          token: ${{secrets.PAT}}
      
      - name: Upload to target 
        run: |
         cd deploy
         cp artifacts/* .
         touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git remote set-url origin https://github.com/prashansatw/demo-workflow-prod.git
          git add .
          git commit -m $GITHUB_SHA
          git push --set-upstream origin main

        

      
        

        


  
  
    

