name: build and deploy
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: "build"

      - run: |
          git clone https://github.com/prashansatw/demo-workflow-test.git  build/pg-website
          build/src/scripts/static.bash 
          git clone https://github.com/DPGAlliance/publicgoods-scripts.git build/pg-scripts 
        
          cd build/pg-scripts 
          npm install 
        
          cd packages/automation 
          node consolidate_data.js  
          cd .. 
          cd ..
          cd ..
          node /src/index.js
          cd registry 
          npm run build
          cd .. 
          cd eligibility 
          npm run build 
          cd .. 
          cd roadmap 
          npm run build 
          cd ..
          ./src/scripts/moveFiles.bash 
          cd .. 

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      # - name: Build
      #   run: |
      #     cd build
      #     npm i
      #     npm run build
      #     cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: artifacts
          path: build/pg-website/*


  # push_to_artifactory:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
      
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v3
  #       with: 
  #         name: artifacts
  #         path: artifacts${{ github.run_number}}/
      
  #     - name: Setup JFrog CLI
  #       id: setup_JFrog_CLI
  #       uses: jfrog/setup-jfrog-cli@v3
  #       env:
  #         JF_URL: ${{ secrets.JF_URL }}
  #         JF_USER: ${{secrets.JF_USER}}
  #         JF_PASSWORD: ${{secrets.JF_PASSWORD}}

  #     - run: |
  #         echo  ${{steps.setup_JFrog_CLI.env.JF_URL}}
  #         jf rt ping --url=https://dpga.jfrog.io/artifactory

  #     - run: jf rt  u "artifacts${{ github.run_number}}/*" demo-app-artifacts

  deploy_to_test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://prashansatw.github.io/demo-workflow-test/

    steps:
      
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with: 
          name: artifacts
          path: artifacts/

      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: prashansatw/demo-workflow-test
          path: "deploy"
          token: ${{secrets.PAT}}

      - name: Push files to target
        run: |
          rm -rf deploy/*
          cp -r artifacts/* deploy
          cd deploy
          # cp build/index.html .
          # cp -r build/static .
          touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git remote set-url origin https://github.com/prashansatw/demo-workflow-test.git
          git add .
          git commit -m $GITHUB_SHA
          git push --set-upstream origin main

  deploy_to_prod:
    needs: deploy_to_test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://prashansatw.github.io/demo-workflow-prod/
    steps:

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with: 
          name: artifacts
          path: artifacts/
      
      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: prashansatw/demo-workflow-prod
          path: "deploy"
          token: ${{secrets.PAT}}
      
      - name: Push to prod
        run: |
          rm -rf deploy/*
          cp -r artifacts/* deploy/
          cd deploy
          touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git remote set-url origin https://github.com/prashansatw/demo-workflow-prod.git
          git add .
          git commit -m $GITHUB_SHA
          git push --set-upstream origin main

    
