name: build and deploy to test
on:
  workflow_dispatch:
  push:
env:
  URL: prashansatw.github.io/demo-workflow-test/

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://${{env.URL}}
    steps:
      - run: echo ${{ secrets.DEV_ENV_SECRET }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: "build"

      - name: Setup JFrog CLI
        id: setup_JFrog_CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}

      - run: |
          echo  ${{steps.setup_JFrog_CLI.env.JF_URL}}
          jf rt ping --retries=100

      - name: Build
        run: |
          cd build
          npm i
          npm run build
          cd ..

      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp

      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: prashansatw/demo-workflow-test
          path: "deploy"
          token: ${{secrets.PAT}}

      - name: Push files to target
        run: |
          rm -rf deploy/*
          cp -r build/* deploy
          cd deploy
          cp build/index.html .
          cp -r build/static .
          touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git remote set-url origin https://github.com/prashansatw/demo-workflow-test.git
          git add .
          git commit -m $GITHUB_SHA
          git push --set-upstream origin main
